-- Add internal/admin fields to properties table
ALTER TABLE public.properties 
ADD COLUMN IF NOT EXISTS owner_address TEXT,
ADD COLUMN IF NOT EXISTS owner_name TEXT,
ADD COLUMN IF NOT EXISTS owner_phone TEXT,
ADD COLUMN IF NOT EXISTS answer_flag BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS dnc_flag BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS neighborhood TEXT,
ADD COLUMN IF NOT EXISTS origem TEXT,
ADD COLUMN IF NOT EXISTS carta TEXT,
ADD COLUMN IF NOT EXISTS zillow_url TEXT,
ADD COLUMN IF NOT EXISTS evaluation TEXT,
ADD COLUMN IF NOT EXISTS focar TEXT,
ADD COLUMN IF NOT EXISTS comparative_price NUMERIC;